
spring:
  application:
    name: yesdrive-directory-impl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.44.252:3306/directory
    username: amdyes
    password: amdyes
    hikari:
      minimum-idle: 32
      maximum-pool-size: 48
server:
  port: 20000
mybatis:
  configuration:
    map-underscore-to-camel-case: true